INSERT INTO USER_DETAILS (ID,BIRTH_DATE,NAME)
VALUES(10001,current_date(),'ASH');
INSERT INTO USER_DETAILS (ID,BIRTH_DATE,NAME)
VALUES(10002,current_date(),'RAVI');
INSERT INTO USER_DETAILS (ID,BIRTH_DATE,NAME)
VALUES(10003,current_date(),'ASHISH');
INSERT INTO POST (ID,DESCRIPTION,USER_ID)
VALUES (20001,'I want to Learn Java',10001);
INSERT INTO POST (ID,DESCRIPTION,USER_ID)
VALUES (20002,'I want to Learn C',10001);
INSERT INTO POST (ID,DESCRIPTION,USER_ID)
VALUES (20003,'I want to Learn Spring',10001);
INSERT INTO POST (ID,DESCRIPTION,USER_ID)
VALUES (20004,'I want to Learn AWS',10001);